spring.application.name=hc
server.port=8088

# --- Base de datos ---
spring.datasource.url=jdbc:postgresql://localhost:5432/hc-service
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
deepseek.api-key=sk-d593e95901ff4619970a5f35067897ef
# --- JPA ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openai.api-key=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
openai.model.vision=gpt-4o
openai.api-url=https://api.openai.com/v1/chat/completions