spring.application.name=hc
server.port=8088

# --- Base de datos ---
spring.datasource.url=jdbc:postgresql://localhost:5432/hc-service
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
deepseek.api-key=sk-d593e95901ff4619970a5f35067897ef
# --- JPA ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jodconverter.local.enabled=drop
jodconverter.local.office-home=C:/Program Files/LibreOffice
jodconverter.local.port-numbers=2002