
spring.application.name=Automatizacion-Service
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/automatizacion-service
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# (no dejes espacios ni comillas)
DEEPSEEK_API_KEY=sk-d593e95901ff4619970a5f35067897ef
